from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SPECIES_FILE = PROJECT_ROOT / "species_names.txt"
DEFAULT_DETECTIONS_DIR = PROJECT_ROOT / "detections"

# TS
# DEFAULT_LATITUDE = 45.65423642845939
# DEFAULT_LONGITUDE = 13.812502298723128

# BERLIN
DEFAULT_LATITUDE = 52.520008
DEFAULT_LONGITUDE = 13.404954

DEFAULT_BATCH_MIN_CONFIDENCE = 0.7
DEFAULT_LIVE_MIN_CONFIDENCE = 0.6
DEFAULT_LIVE_BACKEND = "sounddevice"
DEFAULT_LIVE_DEVICE_INDEX = -1
DEFAULT_BATCH_CLIP_SPAN = "detection"
DEFAULT_LIVE_CLIP_SPAN = "from_detection"

DEFAULT_FRAME_LENGTH = 512*3
DEFAULT_SLICE_INTERVAL = 300
DEFAULT_RECORDER_SAMPLE_RATE = 16000

DEFAULT_HIGH_PASS_HZ = 500.0
DEFAULT_DENOISE_HIGH_PASS_HZ = 150.0
DEFAULT_NOISE_REDUCTION_FACTOR = 2.0
DEFAULT_DENOISE_REDUCTION_FACTOR = 4.0
